# Generated by Django 4.1.1 on 2022-09-08 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_api', '0002_profile_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='operation_in_prgoress',
            field=models.BooleanField(default=False),
        ),
    ]
