# Generated by Django 4.1.1 on 2022-09-08 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile_api', '0003_profile_operation_in_prgoress'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='operation_in_prgoress',
            new_name='operation_in_progress',
        ),
    ]
