# Generated by Django 4.1.1 on 2022-09-09 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_api', '0004_rename_operation_in_prgoress_profile_operation_in_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='gold',
            field=models.IntegerField(default=0),
        ),
    ]
